superhero_database/superhero_database/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/'))
]

superhero_database/superheroes/urls.py
from . import views
from django.urls import path

app_name = 'superheroes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:superhero_id>/', views.detail, name='detail'),
    path('new/', views.create, name='create'),
    path('delete=<int:superhero_id>/', views.delete, name='delete'),
    path('edit=<int:superhero_id>/', views.edit, name='edit'),
]

superhero_database/superheroes/models.py
from django.db import models

# Create your models here.
class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catchphrase = models.CharField(max_length=50)

    def __str__(self):
        return self.name

superhero_database/superheroes/views.py
from django.shortcuts import render
from .models import Superhero
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

# Create your views here.
def index(request):
    all_superheroes = Superhero.objects.all()
    context = {'all_superheroes': all_superheroes}
    return render(request, 'superheroes/index.html', context)

def detail(request, superhero_id):
    one_superhero = Superhero.objects.get(pk=superhero_id)
    context = {'one_superhero': one_superhero}
    return render(request, 'superheroes/detail.html', context)

def create(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        catchphrase = request.POST.get('catchphrase')
        alter_ego = request.POST.get('alter_ego')
        primary_ability = request.POST.get('primary_ability')
        secondary_ability = request.POST.get('secondary_ability')
        new_superhero = Superhero(name=name, catchphrase=catchphrase, alter_ego=alter_ego, primary_ability=primary_ability, secondary_ability=secondary_ability)
        new_superhero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/create.html')

def delete(request, superhero_id):
    delete_superhero = Superhero.objects.get(pk=superhero_id)
    delete_superhero.delete()
    return HttpResponseRedirect(reverse('superheroes:index'))

def edit(request, superhero_id):
    if request.method == 'POST':
        sh = Superhero.objects.get(pk=superhero_id)
        sh.name = request.POST.get('name')
        sh.catchphrase = request.POST.get('catchphrase')
        sh.alter_ego = request.POST.get('alter_ego')
        sh.primary_ability = request.POST.get('primary_ability')
        sh.secondary_ability = request.POST.get('secondary_ability')
        sh.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        edit_superhero = Superhero.objects.get(pk=superhero_id)
        context = {'edit_superhero': edit_superhero}
        return render(request, 'superheroes/edit.html', context)

superhero_database/superheroes/templates/superheroes/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Superheroes - Create</title>
<body>
<div class="container">
    <h1>Add New Superhero</h1>
    <form action="{% url 'superheroes:create' %}" method="post">
        {% csrf_token %}
        <div class="form-floating">
          <input type="text" name="name" id="name" class="form-control" placeholder="Name"><label for="name">Name</label>
        </div>
        <div class="form-floating">
          <input type="text" name="catchphrase" id="catchphrase" class="form-control" placeholder="Catchphrase"><label for="catchphrase">Catchphrase</label>
        </div>
        <div class="form-floating">
          <input type="text" name="alter_ego" id="alter_ego" class="form-control" placeholder="Alter Ego"><label for="alter_ego">Alter Ego</label>
        </div>
        <div class="form-floating">
          <input type="text" name="primary_ability" id="primary_ability" class="form-control" placeholder="Primary Ability"><label for="primary_ability">Primary Ability</label>
        </div>
        <div class="form-floating">
          <input type="text" name="secondary_ability" id="secondary_ability" class="form-control" placeholder="Secondary Ability"><label for="secondary_ability">Secondary Ability</label>
        </div>
        <input type="submit" value="Add New!">
    </form>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

superhero_database/superheroes/templates/superheroes/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Superheroes - Detail</title>
</head>
<body>
<div class="container">
<h1>Superhero Details</h1>
    <div class="card" style="width: 50rem;">
        <!-- <img src="..." class="card-img-top" alt="..."> --!>
        <div class="card-body">
            <h5 class="card-title">{{one_superhero.name}}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{one_superhero.catchphrase}}</h6>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><b>Alter-Ego:</b> {{one_superhero.catchphrase}}</li>
            <li class="list-group-item"><b>Primary Ability:</b> {{one_superhero.primary_ability}}</li>
            <li class="list-group-item"><b>Secondary Ability:</b> {{one_superhero.secondary_ability}}</li>
        </ul>
        <div class="card-body">

        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

superhero_database/superheroes/templates/superheroes/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Superheroes - Edit</title>
</head>
<body>
<div class="container">
    <h1>Edit Superhero</h1>
    <form action="{% url 'superheroes:edit' edit_superhero.id %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="name">Name</label>
            <input type="text" name="name" id="name" class="form-control" value="{{edit_superhero.name}}">
        </div>
        <div class="mb-3">
            <label for="catchphrase">Catchphrase</label>
            <input type="text" name="catchphrase" id="catchphrase" class="form-control" value="{{edit_superhero.catchphrase}}">
        </div>
        <div class="mb-3">
            <label for="alter_ego">Alter Ego</label>
            <input type="text" name="alter_ego" id="alter_ego" class="form-control" value="{{edit_superhero.alter_ego}}">
        </div>
        <div class="mb-3">
            <label for="primary_ability">Primary Ability</label>
            <input type="text" name="primary_ability" id="primary_ability" class="form-control" value="{{edit_superhero.primary_ability}}">
        </div>
        <div class="mb-3">
            <label for="secondary_ability">Secondary Ability</label>
            <input type="text" name="secondary_ability" id="secondary_ability" class="form-control" value="{{edit_superhero.secondary_ability}}">
        </div>
        <input type="submit" value="Save Changes">
    </form>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

superhero_database/superheroes/templates/superheroes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>Superheroes - Index</title>
</head>
<body>
{% load static %}
<div class="container">
<h1>List of Superheroes</h1>
<table class="table table-hover">
    <thead>
        <tr>
            <th>Superhero</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    {% for superhero in all_superheroes %}
    <tr>
    <td>{{superhero.name}}</td><td><a href="{% url 'superheroes:detail' superhero.id %}">See More Details</a></td><td><a href="{% url 'superheroes:edit' superhero.id %}">Edit</a><td><a href="{% url 'superheroes:delete' superhero.id %}">Delete</a></td>
    </tr>
    {% endfor %}
</table>
    <a href="new/" class="btn btn-primary">Add New</a>
<div>
<img src="{% static 'superheroes/ironman.png' %}" alt="Iron Man" class="img-thumbnail">
</div>

</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>